### ISSUE TITLE
Could not log "sql.active_record" event.

### ISSUE THREAD

**Issue by raghubetina** [firstdraft/draft_log#13]
Still getting `Could not log "sql.active_record" event.` in `draft_log` at times. Check out this workspace:

https://ide.c9.io/raghubetina/draft-log-long-output

Try visiting

https://draft-log-long-output-raghubetina.c9users.io/movies/0
c9.io

The long output in the server log is causing many problems

**Comment by murugan-r** [comment]
@raghubetina Fixed the issue for error scenario .

**Comment by arjunvenkat** [comment]
Hi Murugan, it looks like this error still pops up even after updating the new version of draft_log. 

I was able to re-create by cloning down https://github.com/appdev-projects/photogram-auth and performing any action like clicking a link on the navbar.

**Comment by murugan-r** [comment]
@arjunvenkat Looking into it.

**Comment by murugan-r** [comment]
@arjunvenkat Handled the rails 5.0.2 version for activerecord logger. Please take a look.
